---
name: pipeline

on:
  push:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Generate requirements
        run: poetry export -f requirements.txt --without-hashes | sed -e 's/;.*//' > requirements.txt

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        run: terraform fmt -check -recursive -diff

  deploy:
    environment: AWS access
    runs-on: ubuntu-latest
    needs:
      - checks
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Generate requirements
        run: poetry export -f requirements.txt --without-hashes | sed -e 's/;.*//' > requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: terraform apply -auto-approve
